name: Third workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  first:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 19.x, 20.x]

    steps:
      - name: checkout
        uses: actions/checkout@v4.2.2
        
      - name: build
        uses: actions/setup-node@v4.1.0
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: cache
        uses: actions/cache@v4.1.2
        with:
          path: ~/.npm
